### ISSUE TITLE
Adding csv UTF-8 BOM handling possibilities

### ISSUE THREAD

**Issue by hcpeter** [LetPeopleWork/FlowMetricsCSV#5]
Really great tool, thanks for that. 

I ran into issues when my CSV file contained UTF-8 BOM and the code could not handle it. 

I was able to fix the issue, in CsvService.py by adding the following to the CSV opening code: 

(line 14) 
`with open(file_path, 'r', encoding='utf-8-sig') as file:`

I could not push a branch and open a pull request, can you consider adding this to the file? 

Thank you!

**Comment by huserben** [comment]
Hi @hcpeter 

thanks for the input.
Do you happen to know: can I still import "regular" utf-8 files without the BOM when we set this encoding?

If yes, then it makes sense. However, if the assumption is that the files always have the BOM, we might need to make this more configurable.

**Comment by huserben** [comment]
It turns out that was easy, yes "regular" utf-8 files can still be read. I pushed 2d44302 and published a new version: https://pypi.org/project/flowmetricscsv/0.10.5/

You can upgrade by using `python -m pip install --upgrade flowmetricscsv`.

If you don't mind I keep this issue open until you've verified that it works now for you. Thanks a lot for your contribution!

**Comment by hcpeter** [comment]
Hi @huserben 

Thank you, it works! 

I have a tool that generates the CSV file, and I didn't realize that it uses BOM. After I debugged the problem I just saved the CSV without BOM and it worked, but I could not resist the temptation to create a fix for that :)

**Comment by huserben** [comment]
Thanks for your effort. Actually I did face it in the past myself, and just saved the file without BOM too...so I can imagine your work will save some time for others going forward. Thanks a lot for your contribution!
